//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Administrador : Persona, Consultas
{
	public virtual void Generar_Reporte()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Generar_Estadistica()
	{
		throw new System.NotImplementedException();
	}

}

