//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Alumno : Persona, Consultas, Preguntas
{
	public virtual string Carrera
	{
		get;
		set;
	}

	public virtual string Cuatrimestre
	{
		get;
		set;
	}

}

