//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Especialista : Persona, Consultas
{
	public virtual string Tipo_consulta
	{
		get;
		set;
	}

	public virtual void Visualizar_citas()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Realizar_consulta_medica()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Ver_historial()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Ver_antecedentes()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Ver_datosG()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Generar_reporte()
	{
		throw new System.NotImplementedException();
	}

}

