//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Personal : Persona, Preguntas, Consultas
{
	public virtual string Area
	{
		get;
		set;
	}

	public virtual string Turno
	{
		get;
		set;
	}

}

