//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Preguntas
{
	public virtual object Pregunta1
	{
		get;
		set;
	}

	public virtual object Pregunta2
	{
		get;
		set;
	}

	public virtual string Pregunta3
	{
		get;
		set;
	}

	public virtual void Cuestionario()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Verificar_cuestionario()
	{
		throw new System.NotImplementedException();
	}

}

